language: python
python:
    - "3.4"
install:
    - "pip install coveralls"
    - "./test/bootstrap.sh"
script: nosetests --with-coverage --cover-package=rhythmweb,serve,web,rbhandle
after_success:
    - "coveralls"
