language: python
python:
    - "3.4"
install:
    - "pip install coveralls"
    - "./test/bootstrap.sh"
script: nosetests --with-coverage --cover-package=preferences,rbhandle,serve,web,rhythmweb 
after_success:
    - "coveralls"
